name: Testiranje kode

on:
  push:
    branches:
      - main

jobs:
  preveri_obstoj_testne_datoteke:
    runs-on: self-hosted
    steps:
      - name: Preveri obstoj testne datoteke
        run: |
          if [ ! -f "test.py" ]; then
            echo "Testna datoteka test.py ne obstaja." > napaka.txt
            exit 1
          fi

      - name: Shrani napako v artefakt
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: napaka
          path: napaka.txt

  izvedi_teste:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.12.2, 3.12.1]
    
    needs: preveri_obstoj_testne_datoteke
    steps:
      - name: Preberi napako iz artefakta
        uses: actions/download-artifact@v2
        with:
          name: napaka
          path: .

      - name: Preveri obstoj napake
        run: |
          if [ -f napaka.txt ]; then
            cat napaka.txt
            exit 1
          fi
      - name: Nastavi Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Izvedi teste
        run: pytest
